# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('projectName', models.CharField(max_length=20)),
                ('projectUrl', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('projectToken', models.CharField(max_length=500)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserLoginInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserPerf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserLoginInfo')),
            ],
        ),
    ]
