# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170629_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='username',
            new_name='user',
        ),
    ]
