# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170630_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectUrl',
            field=models.CharField(max_length=1000),
        ),
    ]
