# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170706_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gitlabUserId',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
