# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='projectUrl',
            new_name='httpRepoUrl',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='id',
        ),
        migrations.AddField(
            model_name='projects',
            name='projectId',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='sshRepoUrl',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='webUrl',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectName',
            field=models.CharField(max_length=1000),
        ),
    ]
