# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20170707_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='localRepoExist',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='localRepoPath',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectToken',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
