# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_auto_20170711_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='localRepoExist',
            field=models.BooleanField(default=False),
        ),
    ]
