# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0004_auto_20170711_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='project',
        ),
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='log',
            name='projectId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
