# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20170724_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='action',
            new_name='logType',
        ),
        migrations.AddField(
            model_name='log',
            name='pipelineId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
