# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20170802_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='httpRepoUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='projectName',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='sshRepoUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='webUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
