# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0012_auto_20170802_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mainpage.Projects'),
        ),
    ]
