# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_auto_20170802_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='project',
        ),
    ]
