# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0014_remove_log_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='username',
        ),
    ]
