# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0018_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar_uri',
            field=models.CharField(default='http://placehold.it/150x150', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='jobDescription',
            field=models.CharField(default='What does this team member to? Keep it short! This is also a great spot for social links!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='member',
            name='jobTitle',
            field=models.CharField(default='World Destroyer II', max_length=150),
        ),
    ]
